# Generated by Django 5.1 on 2024-09-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='inv_nom',
            field=models.CharField(help_text='Введите инвентарный номер книги', max_length=20, null=True, verbose_name='инвентарный номер  книги'),
        ),
    ]
